<?php

namespace Database\Seeders;

use App\Models\SectionTemplate;
use Illuminate\Database\Seeder;

class SectionTemplateSeeder extends Seeder
{
    public function run(): void
    {
        $templates = [
            // ─── HERO & KARŞILAMA ───
            [
                'key' => 'hero_slider',
                'name' => 'Hero Slider',
                'category' => 'hero',
                'description' => 'Tam ekran görsel slider',
                'icon' => '🎬',
                'sort_order' => 1,
                'allow_multiple' => false,
                'schema' => [
                    'groups' => [
                        ['key' => 'slides', 'label' => 'Slide\'lar'],
                        ['key' => 'settings', 'label' => 'Ayarlar'],
                        ['key' => 'visibility', 'label' => 'Görünürlük'],
                    ],
                    'fields' => [
                        ['key' => 'slides', 'type' => 'repeater', 'label' => 'Slide\'lar', 'group' => 'slides', 'button_label' => 'Slide Ekle', 'fields' => [
                            ['key' => 'image', 'type' => 'image', 'label' => 'Görsel'],
                            ['key' => 'mobile_image', 'type' => 'image', 'label' => 'Mobil Görsel'],
                            ['key' => 'title', 'type' => 'text', 'label' => 'Başlık'],
                            ['key' => 'subtitle', 'type' => 'textarea', 'label' => 'Alt Başlık'],
                            ['key' => 'button_text', 'type' => 'text', 'label' => 'Buton Yazısı'],
                            ['key' => 'button_url', 'type' => 'text', 'label' => 'Buton Linki'],
                            ['key' => 'text_position', 'type' => 'select', 'label' => 'Metin Konumu', 'options' => ['left' => 'Sol', 'center' => 'Orta', 'right' => 'Sağ']],
                        ]],
                        ['key' => 'autoplay', 'type' => 'toggle', 'label' => 'Otomatik Geçiş', 'group' => 'settings', 'default' => true],
                        ['key' => 'autoplay_speed', 'type' => 'number', 'label' => 'Geçiş Süresi (ms)', 'group' => 'settings', 'default' => 5000],
                        ['key' => 'show_dots', 'type' => 'toggle', 'label' => 'Nokta Göstergesi', 'group' => 'settings', 'default' => true],
                        ['key' => 'show_arrows', 'type' => 'toggle', 'label' => 'Ok Butonları', 'group' => 'settings', 'default' => true],
                        ['key' => 'overlay_opacity', 'type' => 'range', 'label' => 'Karartma Oranı', 'group' => 'settings', 'min' => 0, 'max' => 100, 'default' => 30],
                        ['key' => 'transition_effect', 'type' => 'select', 'label' => 'Geçiş Efekti', 'group' => 'settings', 'options' => ['none' => 'Yok', 'fade' => 'Fade', 'slide' => 'Slide', 'zoom' => 'Zoom'], 'default' => 'fade'],
                        ['key' => 'show_on_mobile', 'type' => 'toggle', 'label' => 'Mobilde Göster', 'group' => 'visibility', 'default' => true],
                        ['key' => 'show_on_tablet', 'type' => 'toggle', 'label' => 'Tablette Göster', 'group' => 'visibility', 'default' => true],
                        ['key' => 'show_on_desktop', 'type' => 'toggle', 'label' => 'Masaüstünde Göster', 'group' => 'visibility', 'default' => true],
                    ],
                ],
                'default_settings' => [
                    'autoplay' => true,
                    'autoplay_speed' => 5000,
                    'show_dots' => true,
                    'show_arrows' => true,
                    'overlay_opacity' => 30,
                    'transition_effect' => 'fade',
                    'show_on_mobile' => true,
                    'show_on_tablet' => true,
                    'show_on_desktop' => true,
                    'slides' => [],
                ],
            ],

            [
                'key' => 'video_hero',
                'name' => 'Video Hero',
                'category' => 'hero',
                'description' => 'Video arka planlı hero bölümü',
                'icon' => '🎥',
                'sort_order' => 2,
                'allow_multiple' => false,
                'schema' => [
                    'groups' => [
                        ['key' => 'content', 'label' => 'İçerik'],
                        ['key' => 'settings', 'label' => 'Ayarlar'],
                    ],
                    'fields' => [
                        ['key' => 'video_url', 'type' => 'text', 'label' => 'Video URL', 'group' => 'content'],
                        ['key' => 'poster_image', 'type' => 'image', 'label' => 'Poster Görseli', 'group' => 'content'],
                        ['key' => 'title', 'type' => 'text', 'label' => 'Başlık', 'group' => 'content'],
                        ['key' => 'subtitle', 'type' => 'textarea', 'label' => 'Alt Başlık', 'group' => 'content'],
                        ['key' => 'button_text', 'type' => 'text', 'label' => 'Buton Yazısı', 'group' => 'content'],
                        ['key' => 'button_url', 'type' => 'text', 'label' => 'Buton Linki', 'group' => 'content'],
                        ['key' => 'overlay_opacity', 'type' => 'range', 'label' => 'Karartma Oranı', 'group' => 'settings', 'min' => 0, 'max' => 100, 'default' => 40],
                        ['key' => 'show_on_mobile', 'type' => 'toggle', 'label' => 'Mobilde Göster', 'group' => 'settings', 'default' => true],
                        ['key' => 'show_on_tablet', 'type' => 'toggle', 'label' => 'Tablette Göster', 'group' => 'settings', 'default' => true],
                        ['key' => 'show_on_desktop', 'type' => 'toggle', 'label' => 'Masaüstünde Göster', 'group' => 'settings', 'default' => true],
                    ],
                ],
                'default_settings' => [
                    'overlay_opacity' => 40,
                    'show_on_mobile' => true,
                    'show_on_tablet' => true,
                    'show_on_desktop' => true,
                ],
            ],

            [
                'key' => 'marquee_banner',
                'name' => 'Kayan Yazı Bandı',
                'category' => 'hero',
                'description' => 'Kampanya duyuru bandı',
                'icon' => '📢',
                'sort_order' => 3,
                'allow_multiple' => true,
                'schema' => [
                    'groups' => [
                        ['key' => 'content', 'label' => 'İçerik'],
                        ['key' => 'style', 'label' => 'Stil'],
                    ],
                    'fields' => [
                        ['key' => 'items', 'type' => 'repeater', 'label' => 'Mesajlar', 'group' => 'content', 'button_label' => 'Mesaj Ekle', 'fields' => [
                            ['key' => 'text', 'type' => 'text', 'label' => 'Metin'],
                        ]],
                        ['key' => 'autoplay_speed', 'type' => 'range', 'label' => 'Geçiş Süresi (sn)', 'group' => 'style', 'min' => 2, 'max' => 10, 'default' => 4],
                        ['key' => 'height', 'type' => 'range', 'label' => 'Yükseklik (px)', 'group' => 'style', 'min' => 30, 'max' => 60, 'default' => 41],
                        ['key' => 'bg_color', 'type' => 'color', 'label' => 'Arka Plan Rengi', 'group' => 'style', 'default' => '#ee8bb9'],
                        ['key' => 'text_color', 'type' => 'color', 'label' => 'Yazı Rengi', 'group' => 'style', 'default' => '#ffffff'],
                        ['key' => 'font_size', 'type' => 'range', 'label' => 'Yazı Boyutu (px)', 'group' => 'style', 'min' => 11, 'max' => 18, 'default' => 13],
                        ['key' => 'show_on_mobile', 'type' => 'toggle', 'label' => 'Mobilde Göster', 'group' => 'style', 'default' => true],
                        ['key' => 'show_on_desktop', 'type' => 'toggle', 'label' => 'Masaüstünde Göster', 'group' => 'style', 'default' => true],
                    ],
                ],
                'default_settings' => [
                    'autoplay_speed' => 4,
                    'height' => 41,
                    'bg_color' => '#ee8bb9',
                    'text_color' => '#ffffff',
                    'font_size' => 13,
                    'show_on_mobile' => true,
                    'show_on_desktop' => true,
                    'items' => [],
                ],
            ],

            // ─── ÜRÜN VİTRİNLERİ ───
            [
                'key' => 'product_carousel',
                'name' => 'Ürün Carousel',
                'category' => 'products',
                'description' => 'Kaydırmalı ürün vitrini',
                'icon' => '🛍️',
                'sort_order' => 10,
                'allow_multiple' => true,
                'schema' => [
                    'groups' => [
                        ['key' => 'content', 'label' => 'İçerik'],
                        ['key' => 'header', 'label' => 'Başlık'],
                        ['key' => 'layout', 'label' => 'Düzen'],
                        ['key' => 'visibility', 'label' => 'Görünürlük'],
                    ],
                    'fields' => [
                        ['key' => 'source', 'type' => 'select', 'label' => 'Ürün Kaynağı', 'group' => 'content', 'options' => [
                            'latest' => 'Yeni Gelenler',
                            'featured' => 'Öne Çıkan',
                            'bestseller' => 'Çok Satanlar',
                            'on_sale' => 'İndirimli',
                            'category' => 'Kategoriye Göre',
                            'brand' => 'Markaya Göre',
                            'tag' => 'Etikete Göre',
                            'manual' => 'Manuel Seçim',
                        ], 'default' => 'latest'],
                        ['key' => 'category_id', 'type' => 'entity_select', 'label' => 'Kategori Seç', 'group' => 'content', 'entity' => 'category', 'depends_on' => ['source' => 'category']],
                        ['key' => 'brand_id', 'type' => 'entity_select', 'label' => 'Marka Seç', 'group' => 'content', 'entity' => 'brand', 'depends_on' => ['source' => 'brand']],
                        ['key' => 'tag_id', 'type' => 'entity_select', 'label' => 'Etiket Seç', 'group' => 'content', 'entity' => 'tag', 'depends_on' => ['source' => 'tag']],
                        ['key' => 'product_ids', 'type' => 'entity_select', 'label' => 'Ürünleri Seç', 'group' => 'content', 'entity' => 'product', 'multiple' => true, 'depends_on' => ['source' => 'manual']],
                        ['key' => 'limit', 'type' => 'number', 'label' => 'Ürün Sayısı', 'group' => 'content', 'default' => 10],
                        ['key' => 'title', 'type' => 'text', 'label' => 'Başlık', 'group' => 'header'],
                        ['key' => 'subtitle', 'type' => 'text', 'label' => 'Alt Başlık', 'group' => 'header'],
                        ['key' => 'title_align', 'type' => 'segment', 'label' => 'Başlık Hizalama', 'group' => 'header', 'options' => ['left' => 'Sol', 'center' => 'Orta', 'right' => 'Sağ'], 'default' => 'left'],
                        ['key' => 'show_view_all', 'type' => 'toggle', 'label' => 'Tümünü Gör Linki', 'group' => 'header', 'default' => true],
                        ['key' => 'view_all_url', 'type' => 'text', 'label' => 'Tümünü Gör URL', 'group' => 'header'],
                        ['key' => 'columns', 'type' => 'select', 'label' => 'Sütun Sayısı (Desktop)', 'group' => 'layout', 'options' => ['3' => '3', '4' => '4', '5' => '5'], 'default' => '4'],
                        ['key' => 'layout_type', 'type' => 'select', 'label' => 'Düzen Tipi', 'group' => 'layout', 'options' => ['carousel' => 'Carousel', 'grid' => 'Grid'], 'default' => 'carousel'],
                        ['key' => 'show_arrows', 'type' => 'toggle', 'label' => 'Okları Göster', 'group' => 'layout', 'default' => true, 'depends_on' => ['layout_type' => 'carousel']],
                        ['key' => 'show_dots', 'type' => 'toggle', 'label' => 'Noktaları Göster', 'group' => 'layout', 'default' => false, 'depends_on' => ['layout_type' => 'carousel']],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                        ['key' => 'bg_color', 'type' => 'color', 'label' => 'Arka Plan Rengi', 'group' => 'layout'],
                        ['key' => 'show_on_mobile', 'type' => 'toggle', 'label' => 'Mobilde Göster', 'group' => 'visibility', 'default' => true],
                        ['key' => 'show_on_tablet', 'type' => 'toggle', 'label' => 'Tablette Göster', 'group' => 'visibility', 'default' => true],
                        ['key' => 'show_on_desktop', 'type' => 'toggle', 'label' => 'Masaüstünde Göster', 'group' => 'visibility', 'default' => true],
                    ],
                ],
                'default_settings' => [
                    'source' => 'latest',
                    'limit' => 10,
                    'title' => 'Yeni Gelenler',
                    'subtitle' => '',
                    'title_align' => 'left',
                    'show_view_all' => true,
                    'columns' => '4',
                    'layout_type' => 'carousel',
                    'show_arrows' => true,
                    'show_dots' => false,
                    'spacing_top' => 60,
                    'spacing_bottom' => 60,
                    'show_on_mobile' => true,
                    'show_on_tablet' => true,
                    'show_on_desktop' => true,
                ],
            ],

            [
                'key' => 'product_tabs',
                'name' => 'Ürün Sekmeleri',
                'category' => 'products',
                'description' => 'Sekmeli ürün vitrinleri',
                'icon' => '📑',
                'sort_order' => 11,
                'allow_multiple' => true,
                'schema' => [
                    'groups' => [
                        ['key' => 'tabs', 'label' => 'Sekmeler'],
                        ['key' => 'layout', 'label' => 'Düzen'],
                    ],
                    'fields' => [
                        ['key' => 'tabs', 'type' => 'repeater', 'label' => 'Sekmeler', 'group' => 'tabs', 'button_label' => 'Sekme Ekle', 'fields' => [
                            ['key' => 'title', 'type' => 'text', 'label' => 'Sekme Başlığı'],
                            ['key' => 'source', 'type' => 'select', 'label' => 'Kaynak', 'options' => [
                                'latest' => 'Yeni Gelenler',
                                'featured' => 'Öne Çıkan',
                                'bestseller' => 'Çok Satanlar',
                                'on_sale' => 'İndirimli',
                                'category' => 'Kategoriye Göre',
                                'brand' => 'Markaya Göre',
                                'tag' => 'Etikete Göre',
                                'manual' => 'Manuel Seçim',
                            ]],
                            ['key' => 'category_id', 'type' => 'entity_select', 'label' => 'Kategori Seç', 'entity' => 'category', 'depends_on' => ['source' => 'category']],
                            ['key' => 'brand_id', 'type' => 'entity_select', 'label' => 'Marka Seç', 'entity' => 'brand', 'depends_on' => ['source' => 'brand']],
                            ['key' => 'tag_id', 'type' => 'entity_select', 'label' => 'Etiket Seç', 'entity' => 'tag', 'depends_on' => ['source' => 'tag']],
                            ['key' => 'product_ids', 'type' => 'entity_select', 'label' => 'Ürünleri Seç', 'entity' => 'product', 'multiple' => true, 'depends_on' => ['source' => 'manual']],
                            ['key' => 'limit', 'type' => 'number', 'label' => 'Ürün Sayısı'],
                        ]],
                        ['key' => 'title', 'type' => 'text', 'label' => 'Bölüm Başlığı', 'group' => 'layout'],
                        ['key' => 'subtitle', 'type' => 'text', 'label' => 'Alt Başlık', 'group' => 'layout'],
                        ['key' => 'title_align', 'type' => 'segment', 'label' => 'Başlık Hizalama', 'group' => 'layout', 'options' => ['left' => 'Sol', 'center' => 'Orta', 'right' => 'Sağ'], 'default' => 'left'],
                        ['key' => 'columns', 'type' => 'select', 'label' => 'Sütun Sayısı', 'group' => 'layout', 'options' => ['3' => '3', '4' => '4', '5' => '5'], 'default' => '5'],
                        ['key' => 'rows', 'type' => 'select', 'label' => 'Satır Sayısı', 'group' => 'layout', 'options' => ['1' => '1', '2' => '2', '3' => '3'], 'default' => '2'],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                    ],
                ],
                'default_settings' => [
                    'title' => 'Ürün Vitrinleri',
                    'subtitle' => '',
                    'title_align' => 'left',
                    'columns' => '5',
                    'rows' => '2',
                    'spacing_top' => 60,
                    'spacing_bottom' => 60,
                    'tabs' => [],
                ],
            ],

            // ─── GÖRSEL ALANLAR ───
            [
                'key' => 'category_grid',
                'name' => 'Kategori Grid',
                'category' => 'visual',
                'description' => 'Kategori ızgarası',
                'icon' => '📦',
                'sort_order' => 20,
                'allow_multiple' => true,
                'schema' => [
                    'groups' => [
                        ['key' => 'content', 'label' => 'İçerik'],
                        ['key' => 'header', 'label' => 'Başlık'],
                        ['key' => 'layout', 'label' => 'Düzen'],
                    ],
                    'fields' => [
                        ['key' => 'source', 'type' => 'select', 'label' => 'Kaynak', 'group' => 'content', 'options' => ['all' => 'Tümü', 'root_only' => 'Sadece Ana Kategoriler', 'manual' => 'Manuel Seçim'], 'default' => 'root_only'],
                        ['key' => 'category_ids', 'type' => 'text', 'label' => 'Kategori ID\'leri (virgülle)', 'group' => 'content', 'depends_on' => ['source' => 'manual']],
                        ['key' => 'limit', 'type' => 'number', 'label' => 'Kategori Sayısı', 'group' => 'content', 'default' => 8],
                        ['key' => 'show_count', 'type' => 'toggle', 'label' => 'Ürün Sayısını Göster', 'group' => 'content', 'default' => false],
                        ['key' => 'title', 'type' => 'text', 'label' => 'Başlık', 'group' => 'header'],
                        ['key' => 'subtitle', 'type' => 'text', 'label' => 'Alt Başlık', 'group' => 'header'],
                        ['key' => 'title_align', 'type' => 'segment', 'label' => 'Başlık Hizalama', 'group' => 'header', 'options' => ['left' => 'Sol', 'center' => 'Orta'], 'default' => 'left'],
                        ['key' => 'layout_style', 'type' => 'select', 'label' => 'Görünüm', 'group' => 'layout', 'options' => ['grid-square' => 'Kare Grid', 'grid-round' => 'Yuvarlak', 'overlay' => 'Overlay', 'carousel' => 'Carousel'], 'default' => 'grid-square'],
                        ['key' => 'columns', 'type' => 'select', 'label' => 'Sütun Sayısı', 'group' => 'layout', 'options' => ['3' => '3', '4' => '4', '5' => '5', '6' => '6'], 'default' => '4'],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                        ['key' => 'bg_color', 'type' => 'color', 'label' => 'Arka Plan Rengi', 'group' => 'layout'],
                    ],
                ],
                'default_settings' => [
                    'source' => 'root_only',
                    'limit' => 8,
                    'show_count' => false,
                    'title' => 'Popüler Kategoriler',
                    'title_align' => 'left',
                    'layout_style' => 'grid-square',
                    'columns' => '4',
                    'spacing_top' => 60,
                    'spacing_bottom' => 60,
                ],
            ],

            [
                'key' => 'full_banner',
                'name' => 'Tam Genişlik Banner',
                'category' => 'visual',
                'description' => 'Kampanya / koleksiyon banner',
                'icon' => '🖼️',
                'sort_order' => 21,
                'allow_multiple' => true,
                'schema' => [
                    'groups' => [
                        ['key' => 'content', 'label' => 'İçerik'],
                        ['key' => 'style', 'label' => 'Stil'],
                        ['key' => 'layout', 'label' => 'Düzen'],
                    ],
                    'fields' => [
                        ['key' => 'image', 'type' => 'image', 'label' => 'Banner Görseli', 'group' => 'content'],
                        ['key' => 'mobile_image', 'type' => 'image', 'label' => 'Mobil Görsel', 'group' => 'content'],
                        ['key' => 'title', 'type' => 'text', 'label' => 'Başlık', 'group' => 'content'],
                        ['key' => 'subtitle', 'type' => 'textarea', 'label' => 'Alt Metin', 'group' => 'content'],
                        ['key' => 'button_text', 'type' => 'text', 'label' => 'Buton Yazısı', 'group' => 'content'],
                        ['key' => 'button_url', 'type' => 'text', 'label' => 'Buton Linki', 'group' => 'content'],
                        ['key' => 'layout_type', 'type' => 'select', 'label' => 'Düzen', 'group' => 'style', 'options' => ['split' => 'Split (Metin + Görsel)', 'overlay' => 'Overlay', 'minimal' => 'Minimal (Sadece Görsel)'], 'default' => 'overlay'],
                        ['key' => 'text_position', 'type' => 'segment', 'label' => 'Metin Konumu', 'group' => 'style', 'options' => ['left' => 'Sol', 'center' => 'Orta', 'right' => 'Sağ'], 'default' => 'left'],
                        ['key' => 'bg_color', 'type' => 'color', 'label' => 'Arka Plan Rengi', 'group' => 'style'],
                        ['key' => 'text_color', 'type' => 'color', 'label' => 'Metin Rengi', 'group' => 'style', 'default' => '#ffffff'],
                        ['key' => 'overlay_opacity', 'type' => 'range', 'label' => 'Karartma', 'group' => 'style', 'min' => 0, 'max' => 100, 'default' => 30],
                        ['key' => 'border_radius', 'type' => 'select', 'label' => 'Köşe Yuvarlaklığı', 'group' => 'style', 'options' => ['none' => 'Yok', 'md' => 'Orta (16px)', 'lg' => 'Büyük (32px)'], 'default' => 'none'],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 0],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 0],
                    ],
                ],
                'default_settings' => [
                    'layout_type' => 'overlay',
                    'text_position' => 'left',
                    'text_color' => '#ffffff',
                    'overlay_opacity' => 30,
                    'border_radius' => 'none',
                    'spacing_top' => 0,
                    'spacing_bottom' => 0,
                ],
            ],

            [
                'key' => 'banner_grid',
                'name' => 'Banner Grid',
                'category' => 'visual',
                'description' => 'İkili/üçlü banner grid',
                'icon' => '🖼️',
                'sort_order' => 22,
                'allow_multiple' => true,
                'schema' => [
                    'groups' => [
                        ['key' => 'banners', 'label' => 'Banner\'lar'],
                        ['key' => 'layout', 'label' => 'Düzen'],
                    ],
                    'fields' => [
                        ['key' => 'banners', 'type' => 'repeater', 'label' => 'Banner\'lar', 'group' => 'banners', 'button_label' => 'Banner Ekle', 'fields' => [
                            ['key' => 'image', 'type' => 'image', 'label' => 'Görsel'],
                            ['key' => 'title', 'type' => 'text', 'label' => 'Başlık'],
                            ['key' => 'button_text', 'type' => 'text', 'label' => 'Buton Yazısı'],
                            ['key' => 'button_url', 'type' => 'text', 'label' => 'Buton Linki'],
                        ]],
                        ['key' => 'grid_layout', 'type' => 'select', 'label' => 'Grid Düzeni', 'group' => 'layout', 'options' => ['2-col' => 'İkili (1+1)', '2-1' => 'Üçlü (2+1)', '3-col' => 'Üçlü (1+1+1)'], 'default' => '2-col'],
                        ['key' => 'gap', 'type' => 'range', 'label' => 'Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 32, 'default' => 16],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 40],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 40],
                    ],
                ],
                'default_settings' => [
                    'grid_layout' => '2-col',
                    'gap' => 16,
                    'spacing_top' => 40,
                    'spacing_bottom' => 40,
                    'banners' => [],
                ],
            ],

            [
                'key' => 'collection_grid',
                'name' => 'Koleksiyon Grid',
                'category' => 'visual',
                'description' => 'Lookbook tarzı koleksiyon kartları',
                'icon' => '🏷️',
                'sort_order' => 23,
                'allow_multiple' => true,
                'schema' => [
                    'groups' => [
                        ['key' => 'collections', 'label' => 'Koleksiyonlar'],
                        ['key' => 'header', 'label' => 'Başlık'],
                        ['key' => 'layout', 'label' => 'Düzen'],
                    ],
                    'fields' => [
                        ['key' => 'collections', 'type' => 'repeater', 'label' => 'Koleksiyonlar', 'group' => 'collections', 'button_label' => 'Koleksiyon Ekle', 'fields' => [
                            ['key' => 'image', 'type' => 'image', 'label' => 'Görsel'],
                            ['key' => 'button_text', 'type' => 'text', 'label' => 'Buton Yazısı'],
                            ['key' => 'url', 'type' => 'text', 'label' => 'Link'],
                        ]],
                        ['key' => 'title', 'type' => 'text', 'label' => 'Bölüm Başlığı', 'group' => 'header'],
                        ['key' => 'subtitle', 'type' => 'text', 'label' => 'Alt Başlık', 'group' => 'header'],
                        ['key' => 'title_align', 'type' => 'segment', 'label' => 'Hizalama', 'group' => 'header', 'options' => ['left' => 'Sol', 'center' => 'Orta'], 'default' => 'center'],
                        ['key' => 'show_overlay', 'type' => 'toggle', 'label' => 'Gölgeleme', 'group' => 'layout', 'default' => true],
                        ['key' => 'columns', 'type' => 'select', 'label' => 'Sütun Sayısı', 'group' => 'layout', 'options' => ['2' => '2', '3' => '3', '4' => '4'], 'default' => '3'],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                    ],
                ],
                'default_settings' => [
                    'title' => 'Koleksiyonlar',
                    'title_align' => 'center',
                    'show_overlay' => true,
                    'columns' => '3',
                    'spacing_top' => 60,
                    'spacing_bottom' => 60,
                    'collections' => [],
                ],
            ],

            [
                'key' => 'multi_image_grid',
                'name' => 'Çoklu Görsel Grid',
                'category' => 'visual',
                'description' => 'Manuel görsel, başlık ve link ekleyerek özel grid oluşturun',
                'icon' => '🖼️',
                'sort_order' => 24,
                'allow_multiple' => true,
                'schema' => [
                    'groups' => [
                        ['key' => 'items', 'label' => 'Görseller'],
                        ['key' => 'header', 'label' => 'Başlık'],
                        ['key' => 'layout', 'label' => 'Düzen'],
                    ],
                    'fields' => [
                        ['key' => 'items', 'type' => 'repeater', 'label' => 'Görseller', 'group' => 'items', 'button_label' => 'Görsel Ekle', 'fields' => [
                            ['key' => 'image', 'type' => 'image', 'label' => 'Görsel'],
                            ['key' => 'title', 'type' => 'text', 'label' => 'Başlık'],
                            ['key' => 'url', 'type' => 'text', 'label' => 'Link'],
                        ]],
                        ['key' => 'title', 'type' => 'text', 'label' => 'Bölüm Başlığı', 'group' => 'header'],
                        ['key' => 'subtitle', 'type' => 'text', 'label' => 'Alt Başlık', 'group' => 'header'],
                        ['key' => 'title_align', 'type' => 'segment', 'label' => 'Hizalama', 'group' => 'header', 'options' => ['left' => 'Sol', 'center' => 'Orta'], 'default' => 'left'],
                        ['key' => 'columns', 'type' => 'select', 'label' => 'Sütun Sayısı', 'group' => 'layout', 'options' => ['3' => '3', '4' => '4', '5' => '5', '6' => '6'], 'default' => '4'],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                        ['key' => 'bg_color', 'type' => 'color', 'label' => 'Arka Plan Rengi', 'group' => 'layout'],
                    ],
                ],
                'default_settings' => [
                    'title' => '',
                    'title_align' => 'left',
                    'columns' => '4',
                    'spacing_top' => 60,
                    'spacing_bottom' => 60,
                    'items' => [],
                ],
            ],

            [
                'key' => 'countdown_banner',
                'name' => 'Geri Sayım Banner',
                'category' => 'visual',
                'description' => 'Kampanya geri sayım sayacı',
                'icon' => '⏰',
                'sort_order' => 24,
                'allow_multiple' => true,
                'schema' => [
                    'groups' => [
                        ['key' => 'content', 'label' => 'İçerik'],
                        ['key' => 'style', 'label' => 'Stil'],
                    ],
                    'fields' => [
                        ['key' => 'title', 'type' => 'text', 'label' => 'Başlık', 'group' => 'content'],
                        ['key' => 'subtitle', 'type' => 'text', 'label' => 'Alt Başlık', 'group' => 'content'],
                        ['key' => 'end_date', 'type' => 'text', 'label' => 'Bitiş Tarihi (YYYY-MM-DD HH:mm)', 'group' => 'content'],
                        ['key' => 'button_text', 'type' => 'text', 'label' => 'Buton Yazısı', 'group' => 'content'],
                        ['key' => 'button_url', 'type' => 'text', 'label' => 'Buton Linki', 'group' => 'content'],
                        ['key' => 'bg_image', 'type' => 'image', 'label' => 'Arka Plan Görseli', 'group' => 'style'],
                        ['key' => 'bg_gradient_from', 'type' => 'color', 'label' => 'Gradient Başlangıç', 'group' => 'style', 'default' => '#6366f1'],
                        ['key' => 'bg_gradient_to', 'type' => 'color', 'label' => 'Gradient Bitiş', 'group' => 'style', 'default' => '#f97316'],
                        ['key' => 'text_color', 'type' => 'color', 'label' => 'Metin Rengi', 'group' => 'style', 'default' => '#ffffff'],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'style', 'min' => 0, 'max' => 120, 'default' => 40],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'style', 'min' => 0, 'max' => 120, 'default' => 40],
                    ],
                ],
                'default_settings' => [
                    'title' => '⚡ Flash Sale',
                    'bg_gradient_from' => '#6366f1',
                    'bg_gradient_to' => '#f97316',
                    'text_color' => '#ffffff',
                    'spacing_top' => 40,
                    'spacing_bottom' => 40,
                ],
            ],

            // ─── İÇERİK & PAZARLAMA ───
            [
                'key' => 'info_cards',
                'name' => 'Bilgi Kartları',
                'category' => 'content',
                'description' => 'Avantaj/güven kartları',
                'icon' => '✨',
                'sort_order' => 30,
                'allow_multiple' => true,
                'schema' => [
                    'groups' => [
                        ['key' => 'cards', 'label' => 'Kartlar'],
                        ['key' => 'layout', 'label' => 'Düzen'],
                    ],
                    'fields' => [
                        ['key' => 'cards', 'type' => 'repeater', 'label' => 'Kartlar', 'group' => 'cards', 'button_label' => 'Kart Ekle', 'fields' => [
                            ['key' => 'icon', 'type' => 'text', 'label' => 'İkon (emoji)'],
                            ['key' => 'title', 'type' => 'text', 'label' => 'Başlık'],
                            ['key' => 'description', 'type' => 'text', 'label' => 'Açıklama'],
                        ]],
                        ['key' => 'layout_style', 'type' => 'select', 'label' => 'Görünüm', 'group' => 'layout', 'options' => ['horizontal' => 'Yatay (İkon + Metin)', 'vertical' => 'Dikey (İkon Üstte)', 'minimal' => 'Minimal Bant'], 'default' => 'horizontal'],
                        ['key' => 'columns', 'type' => 'select', 'label' => 'Sütun Sayısı', 'group' => 'layout', 'options' => ['3' => '3', '4' => '4'], 'default' => '4'],
                        ['key' => 'bg_color', 'type' => 'color', 'label' => 'Arka Plan Rengi', 'group' => 'layout'],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 40],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 40],
                    ],
                ],
                'default_settings' => [
                    'layout_style' => 'horizontal',
                    'columns' => '4',
                    'spacing_top' => 40,
                    'spacing_bottom' => 40,
                    'cards' => [
                        ['icon' => '🚚', 'title' => 'Ücretsiz Kargo', 'description' => '500₺ üzeri siparişlerde'],
                        ['icon' => '🔄', 'title' => 'Kolay İade', 'description' => '14 gün iade hakkı'],
                        ['icon' => '🛡️', 'title' => 'Güvenli Ödeme', 'description' => '256-bit SSL'],
                        ['icon' => '💳', 'title' => 'Taksit İmkanı', 'description' => '12 aya varan taksit'],
                    ],
                ],
            ],

            [
                'key' => 'brand_logos',
                'name' => 'Marka Logoları',
                'category' => 'content',
                'description' => 'Marka carousel',
                'icon' => '🏪',
                'sort_order' => 31,
                'allow_multiple' => false,
                'schema' => [
                    'groups' => [
                        ['key' => 'content', 'label' => 'İçerik'],
                        ['key' => 'layout', 'label' => 'Düzen'],
                    ],
                    'fields' => [
                        ['key' => 'source', 'type' => 'select', 'label' => 'Kaynak', 'group' => 'content', 'options' => ['all' => 'Tüm Markalar', 'manual' => 'Manuel Seçim'], 'default' => 'all'],
                        ['key' => 'brand_ids', 'type' => 'text', 'label' => 'Marka ID\'leri (virgülle)', 'group' => 'content', 'depends_on' => ['source' => 'manual']],
                        ['key' => 'limit', 'type' => 'number', 'label' => 'Marka Sayısı', 'group' => 'content', 'default' => 12],
                        ['key' => 'title', 'type' => 'text', 'label' => 'Başlık', 'group' => 'content'],
                        ['key' => 'autoplay', 'type' => 'toggle', 'label' => 'Otomatik Kaydırma', 'group' => 'layout', 'default' => true],
                        ['key' => 'grayscale', 'type' => 'toggle', 'label' => 'Gri Tonlama', 'group' => 'layout', 'default' => true],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 40],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 40],
                    ],
                ],
                'default_settings' => [
                    'source' => 'all',
                    'limit' => 12,
                    'title' => 'Markalarımız',
                    'autoplay' => true,
                    'grayscale' => true,
                    'spacing_top' => 40,
                    'spacing_bottom' => 40,
                ],
            ],

            [
                'key' => 'testimonials',
                'name' => 'Müşteri Yorumları',
                'category' => 'content',
                'description' => 'Yorum carousel',
                'icon' => '💬',
                'sort_order' => 32,
                'allow_multiple' => false,
                'schema' => [
                    'groups' => [
                        ['key' => 'reviews', 'label' => 'Yorumlar'],
                        ['key' => 'header', 'label' => 'Başlık'],
                        ['key' => 'layout', 'label' => 'Düzen'],
                    ],
                    'fields' => [
                        ['key' => 'reviews', 'type' => 'repeater', 'label' => 'Yorumlar', 'group' => 'reviews', 'button_label' => 'Yorum Ekle', 'fields' => [
                            ['key' => 'name', 'type' => 'text', 'label' => 'İsim'],
                            ['key' => 'location', 'type' => 'text', 'label' => 'Konum'],
                            ['key' => 'rating', 'type' => 'number', 'label' => 'Puan (1-5)'],
                            ['key' => 'text', 'type' => 'textarea', 'label' => 'Yorum'],
                            ['key' => 'avatar', 'type' => 'image', 'label' => 'Avatar'],
                        ]],
                        ['key' => 'title', 'type' => 'text', 'label' => 'Başlık', 'group' => 'header'],
                        ['key' => 'subtitle', 'type' => 'text', 'label' => 'Alt Başlık', 'group' => 'header'],
                        ['key' => 'title_align', 'type' => 'segment', 'label' => 'Hizalama', 'group' => 'header', 'options' => ['left' => 'Sol', 'center' => 'Orta'], 'default' => 'center'],
                        ['key' => 'autoplay', 'type' => 'toggle', 'label' => 'Otomatik Geçiş', 'group' => 'layout', 'default' => true],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                    ],
                ],
                'default_settings' => [
                    'title' => 'Müşterilerimiz Ne Diyor?',
                    'title_align' => 'center',
                    'autoplay' => true,
                    'spacing_top' => 60,
                    'spacing_bottom' => 60,
                    'reviews' => [],
                ],
            ],

            [
                'key' => 'newsletter',
                'name' => 'Bülten Abonelik',
                'category' => 'content',
                'description' => 'E-posta toplama formu',
                'icon' => '📧',
                'sort_order' => 33,
                'allow_multiple' => false,
                'schema' => [
                    'groups' => [
                        ['key' => 'content', 'label' => 'İçerik'],
                        ['key' => 'style', 'label' => 'Stil'],
                    ],
                    'fields' => [
                        ['key' => 'title', 'type' => 'text', 'label' => 'Başlık', 'group' => 'content'],
                        ['key' => 'subtitle', 'type' => 'text', 'label' => 'Alt Başlık', 'group' => 'content'],
                        ['key' => 'placeholder', 'type' => 'text', 'label' => 'Input Placeholder', 'group' => 'content'],
                        ['key' => 'button_text', 'type' => 'text', 'label' => 'Buton Yazısı', 'group' => 'content'],
                        ['key' => 'bg_color', 'type' => 'color', 'label' => 'Arka Plan Rengi', 'group' => 'style', 'default' => '#f8fafc'],
                        ['key' => 'text_color', 'type' => 'color', 'label' => 'Metin Rengi', 'group' => 'style', 'default' => '#1e293b'],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'style', 'min' => 0, 'max' => 120, 'default' => 60],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'style', 'min' => 0, 'max' => 120, 'default' => 60],
                    ],
                ],
                'default_settings' => [
                    'title' => 'Yeniliklerden Haberdar Olun',
                    'subtitle' => 'Kampanya ve yeni koleksiyonlardan ilk siz haberdar olun',
                    'placeholder' => 'E-posta adresiniz',
                    'button_text' => 'Abone Ol',
                    'bg_color' => '#f8fafc',
                    'text_color' => '#1e293b',
                    'spacing_top' => 60,
                    'spacing_bottom' => 60,
                ],
            ],

            [
                'key' => 'faq_accordion',
                'name' => 'SSS Accordion',
                'category' => 'content',
                'description' => 'Sıkça sorulan sorular',
                'icon' => '❓',
                'sort_order' => 34,
                'allow_multiple' => true,
                'schema' => [
                    'groups' => [
                        ['key' => 'questions', 'label' => 'Sorular'],
                        ['key' => 'header', 'label' => 'Başlık'],
                        ['key' => 'layout', 'label' => 'Düzen'],
                    ],
                    'fields' => [
                        ['key' => 'questions', 'type' => 'repeater', 'label' => 'Sorular', 'group' => 'questions', 'button_label' => 'Soru Ekle', 'fields' => [
                            ['key' => 'question', 'type' => 'text', 'label' => 'Soru'],
                            ['key' => 'answer', 'type' => 'textarea', 'label' => 'Cevap'],
                        ]],
                        ['key' => 'title', 'type' => 'text', 'label' => 'Başlık', 'group' => 'header'],
                        ['key' => 'title_align', 'type' => 'segment', 'label' => 'Hizalama', 'group' => 'header', 'options' => ['left' => 'Sol', 'center' => 'Orta'], 'default' => 'center'],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 60],
                    ],
                ],
                'default_settings' => [
                    'title' => 'Sıkça Sorulan Sorular',
                    'title_align' => 'center',
                    'spacing_top' => 60,
                    'spacing_bottom' => 60,
                    'questions' => [],
                ],
            ],

            [
                'key' => 'rich_text',
                'name' => 'Zengin Metin',
                'category' => 'content',
                'description' => 'Serbest HTML içerik',
                'icon' => '📝',
                'sort_order' => 35,
                'allow_multiple' => true,
                'schema' => [
                    'groups' => [
                        ['key' => 'content', 'label' => 'İçerik'],
                        ['key' => 'layout', 'label' => 'Düzen'],
                    ],
                    'fields' => [
                        ['key' => 'content', 'type' => 'textarea', 'label' => 'HTML İçerik', 'group' => 'content'],
                        ['key' => 'max_width', 'type' => 'select', 'label' => 'Maksimum Genişlik', 'group' => 'layout', 'options' => ['sm' => 'Dar (640px)', 'md' => 'Orta (768px)', 'lg' => 'Geniş (1024px)', 'full' => 'Tam'], 'default' => 'md'],
                        ['key' => 'text_align', 'type' => 'segment', 'label' => 'Metin Hizalama', 'group' => 'layout', 'options' => ['left' => 'Sol', 'center' => 'Orta'], 'default' => 'left'],
                        ['key' => 'spacing_top', 'type' => 'range', 'label' => 'Üst Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 40],
                        ['key' => 'spacing_bottom', 'type' => 'range', 'label' => 'Alt Boşluk (px)', 'group' => 'layout', 'min' => 0, 'max' => 120, 'default' => 40],
                    ],
                ],
                'default_settings' => [
                    'max_width' => 'md',
                    'text_align' => 'left',
                    'spacing_top' => 40,
                    'spacing_bottom' => 40,
                ],
            ],
        ];

        foreach ($templates as $data) {
            SectionTemplate::updateOrCreate(
                ['key' => $data['key']],
                $data
            );
        }
    }
}
